import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Menu, Dropdown } from 'antd';
import more from '@/assets/icons/more.svg';
import logo from '@/assets/icons/logo3.png';
import arrowLeft from '@/assets/icons/arrow-left.svg';
import buy from '@/assets/icons/buy.svg';
import avatar from '@/assets/img/avatar.jpg';
import { ROUTE_PATHS, ROUTE_PATHS_CUSTOMER } from '@/router';
import { useAuth } from '@/hooks/use-auth';
export default function CustomerHeader() {
    const { user, logoutMutation } = useAuth();
    const menu = (_jsxs(Menu, { children: [_jsx(Menu.Item, { children: _jsx(Link, { to: ROUTE_PATHS_CUSTOMER.PROFILE, children: "Profile" }) }, "0"), _jsx(Menu.Item, { children: _jsx("button", { onClick: () => logoutMutation.mutate(), children: "Logout" }) }, "1")] }));
    return (_jsx("header", { className: "header", children: _jsx("div", { className: "container", children: _jsxs("div", { className: "top-bar", children: [_jsx("button", { className: "top-bar__more d-none d-lg-block js-toggle", "toggle-target": "#navbar", children: _jsx("img", { src: more, alt: "", className: "icon top-bar__more-icon" }) }), _jsxs(Link, { to: ROUTE_PATHS.ROOT, className: "logo top-bar__logo", children: [_jsx("img", { src: logo, alt: "M&B Mart", className: "logo__img top-bar__logo-img" }), _jsx("h1", { className: "logo__title top-bar__logo-title mt-2", children: "M&B Mart" })] }), _jsxs("nav", { className: "navbar hide", id: "navbar", children: [_jsx("button", { className: "navbar__close-btn js-toggle", "toggle-target": "#navbar", children: _jsx("img", { className: "icon", src: arrowLeft, alt: "" }) }), _jsxs("a", { href: "", className: "nav-btn d-none d-md-flex", children: [_jsx("img", { src: buy, alt: "", className: "icon nav-btn__icon" }), _jsx("span", { className: "nav-btn__title", children: "Card" }), _jsx("span", { className: "nav-btn__qnt", children: "3" })] }), _jsxs("ul", { className: "navbar__list js-dropdown-list", children: [_jsx("li", { className: "navbar__item", children: _jsx(Link, { to: ROUTE_PATHS.ROOT, className: "navbar__link", children: "Home" }) }), _jsx("li", { className: "navbar__item", children: _jsx(Link, { to: ROUTE_PATHS.PRODUCT, className: "navbar__link", children: "Product" }) }), _jsx("li", { className: "navbar__item", children: _jsx(Link, { to: ROUTE_PATHS.BLOG, className: "navbar__link", children: "Blog" }) })] })] }), _jsx("div", { className: "navbar__overlay js-toggle", "toggle-target": "#navbar" }), user ? (_jsxs("div", { className: "top-act", children: [_jsxs("div", { className: "top-act__group d-md-none", children: [_jsx("div", { className: "top-act__separate" }), _jsx(Link, { to: ROUTE_PATHS_CUSTOMER.CART, children: _jsxs("button", { className: "top-act__btn", children: [_jsx("img", { src: buy, alt: "", className: "icon top-act__icon" }), _jsx("span", { className: "top-act__title", children: "Cart" })] }) })] }), _jsx(Dropdown, { overlay: menu, trigger: ['click'], placement: "bottomRight", children: _jsx("div", { className: "top-act__user", onClick: (e) => e.preventDefault(), children: _jsx("img", { src: avatar, alt: "", className: "top-act__avatar" }) }) })] })) : (_jsxs("div", { className: "top-act", children: [_jsx(Link, { to: ROUTE_PATHS.LOGIN, className: "btn btn--text d-md-none", children: "Sign in" }), _jsx(Link, { to: ROUTE_PATHS.SIGNUP, className: "top-act__sign-up btn btn--primary", children: "Sign up" })] }))] }) }) }));
}
