import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import heart2 from '@/assets/icons/heart-2.svg';
import trash from '@/assets/icons/trash.svg';
import plus from '@/assets/icons/plus.svg';
import minus from '@/assets/icons/minus.svg';
import item1 from '@/assets/img/product/item-1.png';
import arrowDown2 from '@/assets/icons/arrow-down-2.svg';
export default function FavouriteItem() {
    return (_jsxs("article", { className: "cart-item", children: [_jsx("label", { className: "cart-info__checkbox", children: _jsx("input", { type: "checkbox", name: "shipping-adress", className: "cart-info__checkbox-input", checked: true }) }), _jsx("a", { href: "./product-detail.html", children: _jsx("img", { src: item1, alt: "", className: "cart-item__thumb" }) }), _jsxs("div", { className: "cart-item__content", children: [_jsxs("div", { className: "cart-item__content-left", children: [_jsx("h3", { className: "cart-item__title", children: _jsx("a", { href: "./product-detail.html", children: "Coffee Beans - Espresso Arabica and Robusta Beans" }) }), _jsxs("p", { className: "cart-item__price-wrap", children: ["$47.00 | ", _jsx("span", { className: "cart-item__status", children: "In Stock" })] }), _jsxs("div", { className: "cart-item__ctrl-wrap", children: [_jsxs("div", { className: "cart-item__ctrl cart-item__ctrl--md-block", children: [_jsxs("div", { className: "cart-item__input", children: ["LavAzza", _jsx("img", { className: "icon", src: arrowDown2, alt: "" })] }), _jsxs("div", { className: "cart-item__input", children: [_jsx("button", { className: "cart-item__input-btn", children: _jsx("img", { className: "icon", src: minus, alt: "" }) }), _jsx("span", { children: "1" }), _jsx("button", { className: "cart-item__input-btn", children: _jsx("img", { className: "icon", src: plus, alt: "" }) })] })] }), _jsxs("div", { className: "cart-item__ctrl", children: [_jsxs("button", { className: "cart-item__ctrl-btn", children: [_jsx("img", { src: heart2, alt: "" }), "Save"] }), _jsxs("button", { className: "cart-item__ctrl-btn js-toggle", "toggle-target": "#delete-confirm", children: [_jsx("img", { src: trash, alt: "" }), "Delete"] })] })] })] }), _jsxs("div", { className: "cart-item__content-right", children: [_jsx("p", { className: "cart-item__total-price", children: "$47.00" }), _jsx("button", { className: "cart-item__checkout-btn btn btn--primary btn--rounded", children: "Check Out" })] })] })] }));
}
