import { jsx as _jsx } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import QueryProvider from './lib/react-query/query-provider.tsx';
import { BrowserRouter } from 'react-router-dom';
import { Provider } from 'react-redux';
import { store } from '@/lib/redux-toolkit/store.ts';
import '@/styles/index.css';
import '@/scss/main.scss';
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(Provider, { store: store, children: _jsx(QueryProvider, { children: _jsx(App, {}) }) }) }) }));
